version: "2"
services:
    lb:
      image: dockercloud/haproxy:1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 80:80
      links:
        - nginx
        - php

    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./source:/var/www/html
            - ./config/site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php

    php:
        image: php:7-fpm
        volumes:
            - ./source:/var/www/html
